### ISSUE TITLE
initial repo creation from this template executes the CI and fails

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-tool-repository-template#5]
Maybe this could be made a tiny bit more pleasant to start working with.

https://github.com/martenson/upgraded-octo-couscous/runs/2998339498?check_suite_focus=true

**Comment by bernt-matthias** [comment]
Seems to be because the commit sha is `0000000000000000000000000000000000000000` upon creation. Which leads to `planemo ci_find_repos --changed_in_commit_range 0000000000000000000000000000000000000000.. --exclude packages --exclude deprecated --exclude_from .tt_skip --output repository_list.txt` which fails.

Think this is a case to fix in the planemo-ci-action here https://github.com/galaxyproject/planemo-ci-action/blob/7a7baf8581bb7eb55780e7a7ebf6206e5b322cf2/planemo_ci_actions.sh#L42 .. but I'm not sure yet how.
